import {useEffect,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {flushSync} from 'react-dom';
import {FiArrowRight,FiLock,FiMapPin,FiShield,FiZap} from 'react-icons/fi';
import toast from 'react-hot-toast';
import api,{message} from '../services/api';
import {useAuth} from '../context/AuthContext';
import BangladeshAreaPicker from '../components/BangladeshAreaPicker';

const Shell=({title,text,children,wide=false})=><div className="auth-backdrop min-h-[calc(100vh-64px)] flex items-center justify-center p-4 sm:p-8"><div className={`panel overflow-hidden grid lg:grid-cols-[.9fr_1.1fr] w-full ${wide?'max-w-5xl':'max-w-4xl'}`}><div className="auth-side hidden lg:flex flex-col justify-between p-10 text-white"><div><span className="inline-flex p-3 rounded-2xl bg-primary text-ink shadow-glow"><FiZap size={28}/></span><h2 className="text-white text-4xl mt-8 leading-tight">Power clarity,<br/>wherever you live.</h2><p className="text-slate-300 mt-4">Live schedules and community outage reporting for every corner of Bangladesh.</p></div><div className="flex items-center gap-3 text-sm text-slate-300"><FiShield className="text-primary"/> Secure, verified and community-powered</div></div><div className="p-6 sm:p-10 bg-white"><div className="lg:hidden inline-flex p-2 rounded-xl bg-primary text-ink mb-6"><FiZap size={22}/></div><h1 className="text-3xl sm:text-4xl">{title}</h1><p className="text-slate-500 mt-2 mb-7">{text}</p>{children}</div></div></div>;

export function Login(){const [form,setForm]=useState({email:'',password:''}),[busy,setBusy]=useState(false),{login}=useAuth(),nav=useNavigate();const submit=async e=>{e.preventDefault();setBusy(true);try{const r=await api.post('/auth/login',form);flushSync(()=>login(r.data.data));toast.success('Welcome back');nav(r.data.data.user.role==='admin'?'/admin':'/dashboard',{replace:true})}catch(e){toast.error(message(e))}finally{setBusy(false)}};return <Shell title="Welcome back" text="Sign in to your PowerWatch account"><form onSubmit={submit} className="space-y-4"><label className="form-control"><span className="label-text mb-2 font-medium">Email address</span><input className="field" type="email" placeholder="you@example.com" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="form-control"><span className="label-text mb-2 font-medium">Password</span><input className="field" type="password" placeholder="••••••••" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><div className="text-right"><Link className="link text-sm" to="/forgot-password">Forgot password?</Link></div><button className="btn btn-primary w-full shadow-glow" disabled={busy}>{busy?<span className="loading loading-spinner loading-sm"/>:<FiLock/>}{busy?'Signing in...':'Sign in'}<FiArrowRight/></button><p className="text-center text-sm pt-2">New here? <Link className="link font-semibold" to="/signup">Create account</Link></p></form></Shell>}

function LocationPicker({form,setForm,busy}){const [divisions,setDivisions]=useState([]),[districts,setDistricts]=useState([]),[upazilas,setUpazilas]=useState([]),[loading,setLoading]=useState('divisions'),[error,setError]=useState('');useEffect(()=>{api.get('/locations/divisions').then(r=>setDivisions(r.data.data)).catch(e=>setError(message(e))).finally(()=>setLoading(''))},[]);const chooseDivision=async e=>{const id=e.target.value,item=divisions.find(x=>x.id===id);setForm({...form,division:item?.name||'',district:'',area_name:''});setDistricts([]);setUpazilas([]);if(!id)return;setLoading('districts');try{const r=await api.get(`/locations/districts/${id}`);setDistricts(r.data.data);setError('')}catch(e){setError(message(e))}finally{setLoading('')}};const chooseDistrict=async e=>{const id=e.target.value,item=districts.find(x=>x.id===id);setForm({...form,district:item?.name||'',area_name:''});setUpazilas([]);if(!id)return;setLoading('upazilas');try{const r=await api.get(`/locations/upazilas/${id}`);setUpazilas(r.data.data);setError('')}catch(e){setError(message(e))}finally{setLoading('')}};return <div><div className="flex items-center gap-2 mb-3"><FiMapPin className="text-primary"/><span className="font-semibold">Your service area</span><span className="text-xs text-slate-400">বাংলাদেশ</span></div><div className="grid sm:grid-cols-3 gap-3"><select className="select-field" disabled={busy||loading==='divisions'} onChange={chooseDivision}><option value="">{loading==='divisions'?'Loading...':'Division'}</option>{divisions.map(x=><option value={x.id} key={x.id}>{x.name} — {x.bn_name}</option>)}</select><select className="select-field" disabled={busy||!districts.length||loading==='districts'} onChange={chooseDistrict}><option value="">{loading==='districts'?'Loading...':'District'}</option>{districts.map(x=><option value={x.id} key={x.id}>{x.name} — {x.bn_name}</option>)}</select><select className="select-field" required disabled={busy||!upazilas.length||loading==='upazilas'} value={form.area_name} onChange={e=>setForm({...form,area_name:e.target.value})}><option value="">{loading==='upazilas'?'Loading...':'Upazila / Thana'}</option>{upazilas.map(x=><option value={x.name} key={x.id}>{x.name} — {x.bn_name}</option>)}</select></div>{error&&<p className="text-error text-sm mt-2">Location service: {error}</p>}</div>}

export function Signup(){const [form,setForm]=useState({name:'',email:'',phone:'',password:'',division:'',district:'',area_name:''}),[location,setLocation]=useState(null),[busy,setBusy]=useState(false),nav=useNavigate();const chooseArea=item=>{setLocation(item);setForm(x=>({...x,division:item?.division||'',district:item?.district||'',area_name:item?.name||''}))};const submit=async e=>{e.preventDefault();if(form.password.length<8)return toast.error('Password needs at least 8 characters');setBusy(true);try{await api.post('/auth/signup',form);toast.success('Account created. Please sign in.');nav('/login')}catch(e){toast.error(message(e))}finally{setBusy(false)}};return <Shell wide title="Join PowerWatch" text="Create your account — area selection is optional"><form onSubmit={submit} className="space-y-5"><div className="grid sm:grid-cols-2 gap-4"><label className="form-control"><span className="label-text mb-2 font-medium">Full name</span><input className="field" placeholder="Your name" required disabled={busy} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="form-control"><span className="label-text mb-2 font-medium">Phone number</span><input className="field" placeholder="01XXXXXXXXX" disabled={busy} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="form-control"><span className="label-text mb-2 font-medium">Email address</span><input className="field" type="email" placeholder="you@example.com" required disabled={busy} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="form-control"><span className="label-text mb-2 font-medium">Password</span><input className="field" type="password" minLength="8" placeholder="At least 8 characters" required disabled={busy} onChange={e=>setForm({...form,password:e.target.value})}/></label></div><BangladeshAreaPicker value={location} onChange={chooseArea} disabled={busy} label="Area (optional)"/><button className="btn btn-primary w-full shadow-glow" disabled={busy}>{busy&&<span className="loading loading-spinner loading-sm"/>}{busy?'Creating your account...':'Create my account'}<FiArrowRight/></button><p className="text-center text-sm">Already registered? <Link className="link font-semibold" to="/login">Sign in</Link></p></form></Shell>}

export function Forgot(){const [email,setEmail]=useState(''),[token,setToken]=useState('');const submit=async e=>{e.preventDefault();try{const r=await api.post('/auth/forgot-password',{email});setToken(r.data.data?.reset_token||'');toast.success(r.data.message)}catch(e){toast.error(message(e))}};return <Shell title="Reset access" text="Enter your registered email"><form onSubmit={submit} className="space-y-4"><input className="field" type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="Email address"/><button className="btn btn-primary w-full">Request reset <FiArrowRight/></button>{token&&<div className="alert alert-info text-sm break-all"><span>Development reset link: <Link className="link" to={`/reset-password/${token}`}>continue</Link></span></div>}</form></Shell>}
export function Reset(){const {token}=useParams(),[password,setPassword]=useState(''),nav=useNavigate();const submit=async e=>{e.preventDefault();try{await api.post(`/auth/reset-password/${token}`,{password});toast.success('Password updated');nav('/login')}catch(e){toast.error(message(e))}};return <Shell title="Choose a new password" text="Use at least eight characters"><form onSubmit={submit} className="space-y-4"><input className="field" type="password" minLength="8" required value={password} onChange={e=>setPassword(e.target.value)}/><button className="btn btn-primary w-full">Reset password</button></form></Shell>}
