import {useEffect,useState} from 'react';import {Link,useNavigate,useParams} from 'react-router-dom';import {FiActivity,FiAlertCircle,FiAlertTriangle,FiArrowLeft,FiCalendar,FiCheckCircle,FiClock,FiEdit3,FiMapPin,FiMessageSquare,FiSearch} from 'react-icons/fi';import toast from 'react-hot-toast';import api,{message} from '../services/api';import {useAuth} from '../context/AuthContext';import {ConfirmModal,Empty,PageHeader,Pagination,Spinner,StatCard} from '../components/UI';import BangladeshAreaPicker,{resolveArea} from '../components/BangladeshAreaPicker';
export function UserDashboard(){const [data,setData]=useState();useEffect(()=>{api.get('/dashboard/stats').then(r=>setData(r.data.data))},[]);if(!data)return <Spinner/>;return <div className="page"><PageHeader title="Your power dashboard" subtitle="A local view of interruptions and reports" action={<Link className="btn btn-primary" to="/dashboard/report/new">Report outage</Link>}/><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">{[['Today',data.today,FiCalendar],['Upcoming',data.upcoming,FiClock],['Active',data.active,FiActivity],['Pending reports',data.pending,FiAlertTriangle]].map(x=><StatCard key={x[0]} label={x[0]} value={x[1]} icon={x[2]}/>)}</div><h2 className="text-xl mt-10 mb-4">Recently updated reports</h2>{data.recent.length?<div className="panel overflow-x-auto"><table className="table"><thead><tr><th>Report</th><th>Area</th><th>Status</th><th></th></tr></thead><tbody>{data.recent.map(r=><tr key={r.id}><td>{r.title}</td><td>{r.area.name}</td><td><StatusBadge value={r.status}/></td><td><Link className="btn btn-ghost btn-sm" to={`/dashboard/reports/${r.id}`}>View</Link></td></tr>)}</tbody></table></div>:<Empty text="You have not submitted any reports"/>}</div>}
export function MyReports(){const [rows,setRows]=useState([]),[meta,setMeta]=useState(),[loading,setLoading]=useState(true),[status,setStatus]=useState(''),[page,setPage]=useState(1),[del,setDel]=useState(null);const load=()=>{setLoading(true);api.get('/reports',{params:{status,page}}).then(r=>{setRows(r.data.data);setMeta(r.data.pagination)}).finally(()=>setLoading(false))};useEffect(load,[status,page]);const remove=async()=>{try{await api.delete(`/reports/${del}`);toast.success('Report deleted');setDel(null);load()}catch(e){toast.error(message(e))}};return <div className="page"><PageHeader title="My outage reports" action={<Link className="btn btn-primary" to="/dashboard/report/new">New report</Link>}/><select className="select-field max-w-xs mb-5" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All statuses</option>{['pending','investigating','resolved','rejected'].map(x=><option key={x}>{x}</option>)}</select>{loading?<Spinner/>:rows.length?<div className="grid md:grid-cols-2 gap-4">{rows.map(r=><div className="panel p-5" key={r.id}><div className="flex justify-between"><StatusBadge value={r.status}/><span className="text-sm">#{r.id}</span></div><h2 className="text-lg mt-4">{r.title}</h2><p className="text-sm text-slate-500 mt-1">{r.area.name} · {new Date(r.updated_at).toLocaleDateString()}</p><div className="mt-4 flex gap-2"><Link className="btn btn-sm" to={`/dashboard/reports/${r.id}`}>Details</Link>{r.status==='pending'&&<button className="btn btn-sm btn-error btn-outline" onClick={()=>setDel(r.id)}>Delete</button>}</div></div>)}</div>:<Empty/>}<Pagination meta={meta} onPage={setPage}/><ConfirmModal open={!!del} onCancel={()=>setDel(null)} onConfirm={remove}/></div>}
export function ReportForm(){const {id}=useParams(),editing=!!id,[areas,setAreas]=useState([]),[form,setForm]=useState({title:'',description:'',area_id:''}),nav=useNavigate();useEffect(()=>{api.get('/areas',{params:{limit:100,status:'active'}}).then(r=>setAreas(r.data.data));if(editing)api.get(`/reports/${id}`).then(r=>{const x=r.data.data;setForm({title:x.title,description:x.description,area_id:x.area_id})})},[id]);const submit=async e=>{e.preventDefault();if(form.description.length<10)return toast.error('Description needs at least 10 characters');try{editing?await api.patch(`/reports/${id}`,{...form,area_id:Number(form.area_id)}):await api.post('/reports',{...form,area_id:Number(form.area_id)});toast.success(editing?'Report updated':'Report submitted');nav('/dashboard/reports')}catch(e){toast.error(message(e))}};return <div className="page max-w-2xl"><PageHeader title={editing?'Edit report':'Report an unexpected outage'} subtitle="Give the operations team enough detail to investigate"/><form className="panel p-6 space-y-4" onSubmit={submit}><label className="form-control"><span className="label-text mb-2">Area</span><select className="select-field" required value={form.area_id} onChange={e=>setForm({...form,area_id:e.target.value})}><option value="">Choose area</option>{areas.map(a=><option key={a.id} value={a.id}>{a.name}, {a.district}</option>)}</select></label><label className="form-control"><span className="label-text mb-2">Title</span><input className="field" required minLength="2" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="form-control"><span className="label-text mb-2">What happened?</span><textarea className="textarea textarea-bordered h-36" required minLength="10" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="btn btn-primary">{editing?'Save changes':'Submit report'}</button></form></div>}
const reportStatus={
  pending:{label:'Pending review',Icon:FiClock,eyebrow:'REPORT RECEIVED',title:'Your report is in the queue',note:'The operations team has received your report and will review it shortly.',hero:'from-amber-500 to-orange-500',soft:'bg-amber-50 border-amber-200 text-amber-900',icon:'bg-amber-100 text-amber-700',dot:'bg-amber-500'},
  investigating:{label:'Investigating',Icon:FiSearch,eyebrow:'REVIEW IN PROGRESS',title:'The team is investigating',note:'Your report is being checked by the operations team. We will share an update when more information is available.',hero:'from-sky-600 to-cyan-500',soft:'bg-sky-50 border-sky-200 text-sky-900',icon:'bg-sky-100 text-sky-700',dot:'bg-sky-500'},
  rejected:{label:'Report rejected',Icon:FiAlertCircle,eyebrow:'REVIEW COMPLETE',title:'This report was not accepted',note:'The administrator reviewed this report and provided an explanation below.',hero:'from-rose-600 to-red-500',soft:'bg-rose-50 border-rose-200 text-rose-950',icon:'bg-rose-100 text-rose-700',dot:'bg-rose-500'},
  resolved:{label:'Resolved',Icon:FiCheckCircle,eyebrow:'ISSUE CLOSED',title:'This report has been resolved',note:'The operations team has completed its review and marked the issue as resolved.',hero:'from-emerald-600 to-teal-500',soft:'bg-emerald-50 border-emerald-200 text-emerald-950',icon:'bg-emerald-100 text-emerald-700',dot:'bg-emerald-500'}
};
export function ReportDetails(){
  const {id}=useParams(),[item,setItem]=useState(),[error,setError]=useState('');
  useEffect(()=>{api.get(`/reports/${id}`).then(r=>setItem(r.data.data)).catch(e=>setError(message(e)))},[id]);
  if(error)return <div className="page max-w-4xl"><div className="panel p-10 text-center"><FiAlertCircle className="mx-auto text-4xl text-error"/><h1 className="text-xl mt-4">Could not load this report</h1><p className="text-slate-500 mt-2">{error}</p><Link className="btn mt-5" to="/dashboard/reports">Back to reports</Link></div></div>;
  if(!item)return <Spinner/>;
  const state=reportStatus[item.status]||reportStatus.pending,Icon=state.Icon;
  const reported=new Date(item.reported_at).toLocaleString('en-BD',{dateStyle:'medium',timeStyle:'short'});
  return <div className="page max-w-5xl">
    <div className="flex items-center justify-between gap-4 mb-6">
      <Link to="/dashboard/reports" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-ink transition"><FiArrowLeft/>Back to my reports</Link>
      {item.status==='pending'&&<Link className="btn btn-sm bg-white border-slate-200" to={`/dashboard/reports/${id}/edit`}><FiEdit3/>Edit report</Link>}
    </div>
    <section className={`relative overflow-hidden rounded-3xl bg-gradient-to-br ${state.hero} p-6 sm:p-9 text-white shadow-xl`}>
      <div className="absolute -right-10 -top-14 h-48 w-48 rounded-full bg-white/10"/><div className="absolute right-24 -bottom-20 h-40 w-40 rounded-full bg-black/5"/>
      <div className="relative z-10 max-w-3xl">
        <div className="flex flex-wrap items-center gap-3"><span className="inline-flex items-center gap-2 rounded-full bg-white/20 px-3 py-1.5 text-sm font-bold backdrop-blur"><Icon/>{state.label}</span><span className="text-xs font-bold tracking-widest text-white/75">REPORT #{item.id}</span></div>
        <p className="mt-7 text-xs font-extrabold tracking-[.18em] text-white/70">{state.eyebrow}</p><h1 className="mt-2 text-3xl sm:text-4xl text-white leading-tight">{item.title}</h1><p className="mt-4 max-w-2xl text-white/85 leading-relaxed">{state.note}</p>
      </div>
    </section>
    <div className="grid lg:grid-cols-[1fr_300px] gap-6 mt-6 items-start">
      <main className="space-y-6">
        <article className="panel p-6 sm:p-8"><p className="eyebrow">REPORT DETAILS</p><h2 className="text-2xl mt-2">What happened</h2><p className="mt-5 text-slate-600 text-lg leading-8 whitespace-pre-line">{item.description}</p></article>
        <article className={`rounded-2xl border p-6 sm:p-7 ${state.soft}`}>
          <div className="flex items-start gap-4"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${state.icon}`}><FiMessageSquare size={20}/></span><div><p className="text-xs font-extrabold tracking-[.16em] opacity-60">ADMIN RESPONSE</p><h2 className="text-xl mt-1">{item.admin_response?'Update from the operations team':'Waiting for an update'}</h2><p className="mt-3 leading-7 opacity-80">{item.admin_response||'No response has been added yet. You can return to this page later to see the latest update.'}</p></div></div>
        </article>
      </main>
      <aside className="panel p-6 lg:sticky lg:top-24">
        <h2 className="text-lg">Report overview</h2><div className="mt-6 space-y-6">
          <div className="flex gap-3"><span className={`mt-1 h-3 w-3 shrink-0 rounded-full ${state.dot} ring-4 ring-slate-100`}/><div><p className="text-xs font-bold tracking-wider text-slate-400">CURRENT STATUS</p><p className="font-semibold mt-1">{state.label}</p></div></div>
          <div className="flex gap-3"><FiMapPin className="mt-1 shrink-0 text-slate-400"/><div><p className="text-xs font-bold tracking-wider text-slate-400">AREA</p><p className="font-semibold mt-1">{item.area.name}</p><p className="text-sm text-slate-500">{item.area.district}</p></div></div>
          <div className="flex gap-3"><FiCalendar className="mt-1 shrink-0 text-slate-400"/><div><p className="text-xs font-bold tracking-wider text-slate-400">REPORTED</p><p className="font-semibold mt-1">{reported}</p></div></div>
        </div>
      </aside>
    </div>
  </div>
}
export function Profile(){const {user,setUser}=useAuth(),[areas,setAreas]=useState([]),[form,setForm]=useState({name:user.name,phone:user.phone||'',area_id:user.area_id||''});useEffect(()=>{api.get('/areas',{params:{limit:100,status:'active'}}).then(r=>setAreas(r.data.data))},[]);const submit=async e=>{e.preventDefault();try{const r=await api.patch('/auth/profile',{...form,area_id:form.area_id?Number(form.area_id):null});setUser(r.data.data);toast.success('Profile updated')}catch(e){toast.error(message(e))}};return <div className="page max-w-2xl"><PageHeader title="Profile settings"/><form onSubmit={submit} className="panel p-6 space-y-4"><input className="field" value={form.name} required onChange={e=>setForm({...form,name:e.target.value})}/><input className="field" value={user.email} disabled/><input className="field" placeholder="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><select className="select-field" value={form.area_id} onChange={e=>setForm({...form,area_id:e.target.value})}><option value="">No area</option>{areas.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select><button className="btn btn-primary">Save profile</button></form></div>}

export function ReportFormAllAreas(){const {id}=useParams(),editing=!!id,[location,setLocation]=useState(null),[form,setForm]=useState({title:'',description:''}),nav=useNavigate();useEffect(()=>{if(editing)api.get(`/reports/${id}`).then(r=>{const x=r.data.data;setForm({title:x.title,description:x.description});setLocation({name:x.area.name,district:x.area.district,division:x.area.zone})})},[id]);const submit=async e=>{e.preventDefault();if(!location)return toast.error('Please select an area');if(form.description.length<10)return toast.error('Description needs at least 10 characters');try{const area=await resolveArea(location),data={...form,area_id:area.id};editing?await api.patch(`/reports/${id}`,data):await api.post('/reports',data);toast.success(editing?'Report updated':'Report submitted');nav('/dashboard/reports')}catch(e){toast.error(message(e))}};return <div className="page max-w-2xl"><PageHeader title={editing?'Edit report':'Report an unexpected outage'} subtitle="Select any Bangladesh area and describe the issue"/><form className="panel p-6 space-y-4" onSubmit={submit}><BangladeshAreaPicker value={location} onChange={setLocation} required/><label className="form-control"><span className="label-text mb-2">Title</span><input className="field" required minLength="2" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="form-control"><span className="label-text mb-2">What happened?</span><textarea className="textarea textarea-bordered h-36" required minLength="10" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="btn btn-primary">{editing?'Save changes':'Submit report'}</button></form></div>}

export function ProfileAllAreas(){const {user,setUser}=useAuth(),[location,setLocation]=useState(user.area?{name:user.area.name,district:user.area.district,division:user.area.zone}:null),[form,setForm]=useState({name:user.name,phone:user.phone||''});const submit=async e=>{e.preventDefault();try{const area=location?await resolveArea(location):null;const r=await api.patch('/auth/profile',{...form,area_id:area?.id||null});setUser(r.data.data);toast.success('Profile updated')}catch(e){toast.error(message(e))}};return <div className="page max-w-2xl"><PageHeader title="Profile settings"/><form onSubmit={submit} className="panel p-6 space-y-4"><input className="field" value={form.name} required onChange={e=>setForm({...form,name:e.target.value})}/><input className="field" value={user.email} disabled/><input className="field" placeholder="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><BangladeshAreaPicker value={location} onChange={setLocation}/><button className="btn btn-primary">Save profile</button></form></div>}
