import {FiAlertCircle,FiChevronLeft,FiChevronRight,FiSearch,FiZap} from 'react-icons/fi';
export const Spinner=()=> <div className="flex justify-center p-12"><span className="loading loading-spinner loading-lg text-primary"/></div>;
export const Empty=({text='Nothing found'})=><div className="panel p-12 text-center text-slate-500"><FiZap className="mx-auto text-4xl mb-3 text-primary"/><p>{text}</p></div>;
export const ErrorState=({text})=><div className="alert alert-error"><FiAlertCircle/>{text}</div>;
export const StatusBadge=({value})=><span className={`badge ${['resolved','completed','active'].includes(value)?'badge-success':['ongoing','investigating'].includes(value)?'badge-info':['cancelled','rejected','inactive'].includes(value)?'badge-error':'badge-warning'} badge-outline capitalize`}>{value}</span>;
export const PageHeader=({title,subtitle,action})=><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 mb-7"><div><h1 className="text-3xl">{title}</h1>{subtitle&&<p className="text-slate-500 mt-1">{subtitle}</p>}</div>{action}</div>;
export const SearchInput=({value,onChange})=><label className="input input-bordered bg-white flex items-center gap-2"><FiSearch/><input value={value} onChange={e=>onChange(e.target.value)} placeholder="Search..."/></label>;
export function Pagination({meta,onPage}){if(!meta||meta.totalPages<=1)return null;return <div className="flex items-center justify-between mt-6"><span className="text-sm text-slate-500">Page {meta.page} of {meta.totalPages} · {meta.total} items</span><div className="join"><button className="btn btn-sm join-item" disabled={meta.page<=1} onClick={()=>onPage(meta.page-1)}><FiChevronLeft/></button><button className="btn btn-sm join-item" disabled={meta.page>=meta.totalPages} onClick={()=>onPage(meta.page+1)}><FiChevronRight/></button></div></div>}
export function ConfirmModal({open,title='Are you sure?',onCancel,onConfirm}){if(!open)return null;return <div className="modal modal-open"><div className="modal-box"><h3 className="text-xl">{title}</h3><p className="py-4 text-slate-500">This action cannot be undone.</p><div className="modal-action"><button className="btn" onClick={onCancel}>Cancel</button><button className="btn btn-error" onClick={onConfirm}>Delete</button></div></div></div>}
export const StatCard=({label,value,icon:Icon})=><div className="panel p-5"><div className="flex justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="text-3xl font-bold mt-2">{value??0}</p></div>{Icon&&<div className="p-3 h-fit rounded-xl bg-amber-100 text-amber-700"><Icon size={22}/></div>}</div></div>;
